# -*- coding: utf-8 -*-
"""ms671-projeto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1936xfkntd6MyqQI8Ox6AnOHljNeGVlnV

#**Projeto 02 - Introdução ao Aprendizado de Máquina Profundo (MS671)**

- Gustavo Coimbra de Souza Teixeira - RA: 237599
- Julia Folgueral - RA: 277178
- Luiz Fernando de Oliveira Pereira - RA: 267356
- Maria Eduarda Villéla Silva - RA: 212974

# Tradução Automática de Datas com Atenção + LSTM

**DICA:** ANTES DE RODAR OS CÓDIGOS, VÁ EM "Ambiente de execução" --> "Alterar o tipo de ambiente de execução" E ALTERE A CPU PARA GPUT4. Isso vai fazer os códigos rodarem mais rápido.

**Descrição:** Modelo de sequência para sequência (seq2seq) com mecanismo de atenção baseado em Bi-LSTM para converter datas do formato humano (ex: `"21th of August 2016"`) para o formato máquina (`"2016-08-21"`).

---
> Execute as células **em ordem**. Comece pela **Célula 1** para ler os arquivos do Drive.

## 1. Ler os arquivos do drive
"""

# BAIXAR OS ARQUIVOS DA PASTA DO GOOGLE DRIVE
!pip -q install gdown

import gdown
import os

# Pasta local
FILE_DIR = "./MS671-P2/MS671-P2/"

# Baixa a pasta apenas se ela ainda não existir
if not os.path.exists(FILE_DIR):
    gdown.download_folder(
        id="1YPDUPxnM9j5bGGBiFHg6bi4doPe73kRM",
        output=FILE_DIR,
        quiet=False,
        use_cookies=False
    )

print("Arquivos encontrados na pasta:")
for f in os.listdir(FILE_DIR):
    print(f"  {f}")

"""## 2. Importações"""

import numpy as np
import pickle
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, LSTM, Bidirectional, Dense, RepeatVector,
    Concatenate, Activation, Dot, Lambda
)
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

print("TensorFlow:", tf.__version__)

"""## 3. Carregamento dos Dados e Vocabulários"""

def carregar_pickle(caminho):
    with open(caminho, 'rb') as f:
        return pickle.load(f)

dataset           = carregar_pickle(FILE_DIR + 'MS671-P2/dataset.pkl')
human_vocab       = carregar_pickle(FILE_DIR + 'MS671-P2/human_vocab.pkl')
machine_vocab     = carregar_pickle(FILE_DIR + 'MS671-P2/machine_vocab.pkl')
inv_machine_vocab = carregar_pickle(FILE_DIR + 'MS671-P2/inv_machine_vocab.pkl')

print(f"Exemplos no dataset : {len(dataset)}")
print(f"Vocab humano        : {len(human_vocab)} caracteres")
print(f"Vocab máquina       : {len(machine_vocab)} caracteres")
print(f"\nPrimeiros 5 exemplos:")
for h, m in dataset[:5]:
    print(f"  '{h}'  →  '{m}'")

print(f"\nVocab máquina : {machine_vocab}")
print(f"Vocab humano  : {human_vocab}")

"""## 4. Parâmetros Globais"""

Tx = 30   # Comprimento fixo da entrada  (formato humano)
Ty = 10   # Comprimento fixo da saída    (YYYY-MM-DD = 10 chars)

n_a = len(human_vocab)    # Tamanho do vocabulário de entrada
n_y = len(machine_vocab)  # Tamanho do vocabulário de saída

print(f"Tx={Tx}, Ty={Ty}, n_a={n_a}, n_y={n_y}")

"""## 5. Pré-processamento: `string_to_int` e Codificação One-Hot"""

# FUNÇÕES DE PRÉ-PROCESSAMENTO

def string_to_int(string, length, vocab):
    """
    Converte uma string em lista de inteiros usando o vocab fornecido.
    - Padeia com vocab['<pad>'] se a string for curta demais.
    - Trunca se for longa demais.
    - Usa vocab['<unk>'] para caracteres desconhecidos.
    """
    string = string.lower().replace(',', '')

    if len(string) > length:
        string = string[:length]

    rep = [vocab.get(c, vocab.get('<unk>', 0)) for c in string]

    if len(string) < length:
        rep += [vocab['<pad>']] * (length - len(string))

    return rep


def preparar_dataset(dataset, human_vocab, machine_vocab, Tx, Ty):
    """
    Converte todos os pares do dataset em arrays numpy one-hot.

    Retorna:
        X  : (m, Tx, n_a)  — entradas one-hot
        Y  : (m, Ty, n_y)  — saídas one-hot
        Xr : (m, Tx)       — entradas como índices (para to_categorical)
    """
    m   = len(dataset)
    n_a = len(human_vocab)
    n_y = len(machine_vocab)

    X  = np.zeros((m, Tx, n_a),  dtype=np.float32)
    Y  = np.zeros((m, Ty, n_y),  dtype=np.float32)

    for i, (human, machine) in enumerate(dataset):
        # Entrada
        idx_x = string_to_int(human, Tx, human_vocab)
        for t, idx in enumerate(idx_x):
            X[i, t, idx] = 1.0

        # Saída
        idx_y = string_to_int(machine, Ty, machine_vocab)
        for t, idx in enumerate(idx_y):
            Y[i, t, idx] = 1.0

    return X, Y


X, Y = preparar_dataset(dataset, human_vocab, machine_vocab, Tx, Ty)
print(f"X shape: {X.shape}   Y shape: {Y.shape}")

"""## 6. Construção do Modelo de Atenção + LSTM"""

# Construção do Modelo
# ARQUITETURA (baseada no diagrama do projeto e usando plot_attention_map):
#
#  Entrada one-hot (Tx, n_a)
#       │
#  [Bi-LSTM] n_units_pre unidades  ← camada índice 2
#       │  anotações a^<t>  shape: (Tx, 2*n_units_pre)
#       │
#  Para cada passo t' = 1..Ty:
#    RepeatVector(Tx)(s)            ← camada índice 3
#    Concatenate([a, s_rep])        ← camada índice 4
#    Dense(10, tanh)  → energias e  ← camada índice 5
#    Dense(1, linear) → scores      ← camada índice 6
#    Softmax → α  (atenção)         ← camada índice 7   nome: 'attention_weights'
#    Dot([α, a])  → context         ← camada índice 8
#    [LSTM pós-atenção]             ← camada índice 10
#    Dense(n_y, softmax) → y^<t'>
#
# Note que a ordem e os nomes das camadas foram escolhidos para serem
# compatíveis com a função plot_attention_map.

def construir_modelo(Tx, Ty, n_a, n_y, n_units_pre=32, n_units_post=64):
    """
    Constrói o modelo de tradução com mecanismo de atenção.

    Parâmetros:
        Tx, Ty        : comprimentos das sequências
        n_a, n_y      : tamanhos dos vocabulários
        n_units_pre   : unidades na Bi-LSTM (pré-atenção)
        n_units_post  : unidades na LSTM (pós-atenção)  ← equivale a n_s

    Retorna:
        model : Model Keras compilado
    """


    # Camadas reutilizadas (definidas uma vez, chamadas Ty vezes)
    # A ordem de definição determina o índice das camadas no modelo.

    # Pré-atenção: Bi-LSTM — índice 2 no modelo final
    bilstm = Bidirectional(
        LSTM(n_units_pre, return_sequences=True),
        name='bidirectional_pre_attn'
    )

    # Atenção — índices 3..8
    repeat   = RepeatVector(Tx)                                   # idx 3
    concat   = Concatenate(axis=-1)                               # idx 4
    dense_e1 = Dense(10, activation='tanh',   name='dense_tanh') # idx 5
    dense_e2 = Dense(1,  activation='linear', name='dense_score') # idx 6
    # Softmax sobre o eixo Tx (posições de entrada).
    # Activation('softmax') aplica sobre o último eixo (tamanho 1), gerando aviso.
    # Correçaõ feita com um Lambda que aplica sobre axis=1 (o eixo de comprimento Tx).
    softmax_alpha = Lambda(lambda x: tf.nn.softmax(x, axis=1), name='attention_weights')  # idx 7
    dot_ctx  = Dot(axes=1)                                        # idx 8

    # Pós-atenção: LSTM - índice 10 (índice 9 é ocupado pela concatenação
    # interna do Dot/Reshape; pode variar)
    lstm_post = LSTM(n_units_post, return_state=True, name='post_attn_lstm')

    # Saída
    dense_out = Dense(n_y, activation='softmax', name='saida')


    # Entradas
    X_in = Input(shape=(Tx, n_a),      name='entrada')      # idx 0
    s0   = Input(shape=(n_units_post,), name='s0')            # idx 1 (parte)
    c0   = Input(shape=(n_units_post,), name='c0')


    # Pré-atenção: processa toda a sequência de entrada
    a = bilstm(X_in)   # shape: (batch, Tx, 2*n_units_pre)

    # Estados iniciais da LSTM de pós-atenção
    s = s0
    c = c0


    # Loop de decodificação
    saidas = []

    for t in range(Ty):

        # 1. Repete o estado oculto anterior para cada posição de entrada
        s_rep = repeat(s)                   # (batch, Tx, n_units_post)

        # 2. Concatena com as anotações da Bi-LSTM
        #    Ordem [a, s_rep] — compatível com plot_attention_map (camada 4)
        concat_as = concat([a, s_rep])      # (batch, Tx, 2*n_units_pre + n_units_post)

        # 3. Score de energia
        e = dense_e1(concat_as)             # (batch, Tx, 10)
        e = dense_e2(e)                     # (batch, Tx, 1)

        # 4. Pesos de atenção (softmax sobre Tx)
        alpha = softmax_alpha(e)            # (batch, Tx, 1) — softmax sobre Tx posições

        # 5. Vetor de contexto (soma ponderada das anotações)
        context = dot_ctx([alpha, a])       # (batch, 1, 2*n_units_pre)

        # 6. LSTM de pós-atenção
        s, _, c = lstm_post(context, initial_state=[s, c])

        # 7. Projeção na saída
        y_t = dense_out(s)                  # (batch, n_y)
        saidas.append(y_t)


    # Monta o modelo
    model = Model(inputs=[X_in, s0, c0], outputs=saidas, name='atencao_lstm')

    model.compile(
        optimizer=Adam(learning_rate=0.005),
        loss='categorical_crossentropy',
        metrics=[['accuracy']] * Ty   # uma lista de métricas por saída
    )

    return model


# Hiperparâmetros base
n_units_pre  = 32
n_units_post = 64

model = construir_modelo(Tx, Ty, n_a, n_y, n_units_pre, n_units_post)
model.summary()

# Inspeciona os índices reais das camadas
print("\nÍndices das camadas:")
for i, layer in enumerate(model.layers):
    try:
        shape = layer.output_shape
    except AttributeError:
        shape = "(sem output_shape)"
    print(f"  [{i:2d}] {layer.name:<35} output: {shape}")

"""## 7. Funções Auxiliares de Treino e Inferência"""

def saidas_por_passo(Y):
    """Reformata Y de (m, Ty, n_y) para lista de Ty arrays (m, n_y)."""
    return [Y[:, t, :] for t in range(Y.shape[1])]


def estados_zeros(m, n_units_post):
    """Estados iniciais zerados para a LSTM de pós-atenção."""
    return np.zeros((m, n_units_post)), np.zeros((m, n_units_post))


def traduzir(texto, model, human_vocab, inv_machine_vocab,
             Tx, Ty, n_a, n_units_post):
    """
    Traduz uma data do formato humano para o formato máquina (YYYY-MM-DD).
    """
    idx_x  = string_to_int(texto, Tx, human_vocab)
    X_test = np.array([to_categorical(idx_x, num_classes=n_a)])  # (1, Tx, n_a)

    s0, c0 = estados_zeros(1, n_units_post)
    preds  = model.predict([X_test, s0, c0], verbose=0)

    resultado = ''.join(
        inv_machine_vocab[np.argmax(preds[t][0])] for t in range(Ty)
    )
    return resultado

"""## 8. Treinamento do Zero por 1 Época"""

print("=" * 65)
print("ITEM 2 — TREINAMENTO DO ZERO: 1 ÉPOCA")
print("=" * 65)

m = X.shape[0]
s0_tr, c0_tr = estados_zeros(m, n_units_post)
Y_lista      = saidas_por_passo(Y)

historico_1ep = model.fit(
    [X, s0_tr, c0_tr],
    Y_lista,
    epochs=1,
    batch_size=128,
    verbose=1
)

datas_teste = [
    "3 May 1979",
    "5 April 09",
    "21th of August 2016",
    "Tue 10 Jul 2007",
    "Saturday May 9 2018",
    "March 27, 2011",
    "monday january 17 2000",
    "9/10/70",
]

print("\nResultados após 1 época:")
print(f"  {'Entrada':<30}  {'Predição':^12}  {'Esperado'}")
print("  " + "-" * 60)
for h, m_ref in dataset[:8]:
    pred = traduzir(h, model, human_vocab, inv_machine_vocab,
                    Tx, Ty, n_a, n_units_post)
    print(f"  {h:<30}  {pred:^12}  {m_ref}")

"""## 9. Treinamento do Zero por 50 Épocas

⚠️ Esse chunck pode demorar alguns minutos para rodar.
"""

print("\n" + "=" * 65)
print("ITEM 2 — TREINAMENTO DO ZERO: 50 ÉPOCAS")
print("=" * 65)

# Reconstrói com pesos aleatórios
model_50 = construir_modelo(Tx, Ty, n_a, n_y, n_units_pre, n_units_post)
m_total  = X.shape[0]
s0_tr50, c0_tr50 = estados_zeros(m_total, n_units_post)

historico_50ep = model_50.fit(
    [X, s0_tr50, c0_tr50],
    Y_lista,
    epochs=50,
    batch_size=128,
    verbose=1
)

print("\nResultados após 50 épocas:")
print(f"  {'Entrada':<30}  {'Predição':^12}  {'Esperado'}")
print("  " + "-" * 60)
for h, m_ref in dataset[:8]:
    pred = traduzir(h, model_50, human_vocab, inv_machine_vocab,
                    Tx, Ty, n_a, n_units_post)
    print(f"  {h:<30}  {pred:^12}  {m_ref}")

# Gráfico da curva de aprendizado
acc_keys = [k for k in historico_50ep.history if 'accuracy' in k]
acc_medio = np.mean([historico_50ep.history[k] for k in acc_keys], axis=0)

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
ax1.plot(historico_50ep.history['loss'], color='steelblue')
ax1.set_title('Loss — 50 épocas'); ax1.set_xlabel('Época'); ax1.set_ylabel('Loss')
ax1.grid(alpha=0.3)

ax2.plot(acc_medio, color='seagreen')
ax2.set_title('Acurácia média — 50 épocas'); ax2.set_xlabel('Época'); ax2.set_ylabel('Acurácia')
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig('/content/curva_50ep.png', dpi=150)
plt.show()
print("Gráfico salvo em /content/curva_50ep.png")

"""## 10. Modelo Pré-Treinado (`model.h5`)"""

print("\n" + "=" * 65)
print("ITEM 2 — MODELO PRÉ-TREINADO (model.h5)")
print("=" * 65)

# O modelo.h5 (disponiblizado pelo professor) foi treinado com n_s=64.
# Tenta carregar os pesos na nossa arquitetura equivalente.
# Se houver divergência de shape, o except usa load_model direto.

try:
    model_pre = construir_modelo(Tx, Ty, n_a, n_y,
                                  n_units_pre=32, n_units_post=64)
    model_pre.load_weights(FILE_DIR + 'MS671-P2/model.h5')
    print("✓ Pesos carregados com sucesso via load_weights!")
    n_units_post_pre = 64

except Exception as err:
    print(f"load_weights falhou ({err})\nTentando load_model...")
    model_pre = tf.keras.models.load_model(FILE_DIR + 'MS671-P2/model.h5')
    print("✓ Modelo carregado via load_model!")
    # Infere n_units_post a partir do modelo carregado
    n_units_post_pre = model_pre.layers[-2].output_shape[-1]
    print(f"  n_units_post detectado: {n_units_post_pre}")

print("\nResultados do modelo pré-treinado:")
print(f"  {'Entrada':<30}  {'Predição':^12}  {'Esperado'}")
print("  " + "-" * 60)
for h, m_ref in dataset[:8]:
    pred = traduzir(h, model_pre, human_vocab, inv_machine_vocab,
                    Tx, Ty, n_a, n_units_post_pre)
    print(f"  {h:<30}  {pred:^12}  {m_ref}")

"""## 11. Variando o Número de Unidades

⚠️Esse chunck pode demorar alguns minutos para rodar.
"""

print("\n" + "=" * 65)
print("ITEM 3 — VARIANDO NÚMERO DE UNIDADES")
print("=" * 65)

# Configurações para comparações: (n_units_pre, n_units_post, descrição)
configuracoes = [
    (8,  32,  "Muito pequeno (8 pré,  32 pós)"),
    (16, 32,  "Pequeno       (16 pré, 32 pós)"),
    (32, 64,  "Base          (32 pré, 64 pós)  ← configuração padrão"),
    (64, 128, "Grande        (64 pré, 128 pós)"),
]

datas_item3 = [
    ("3 May 1979",          "1979-05-03"),
    ("21th of August 2016", "2016-08-21"),
    ("March 27, 2011",      "2011-03-27"),
    ("Tue 10 Jul 2007",     "2007-07-10"),
]

resultados_cfg = {}

for n_pre, n_pos, desc in configuracoes:
    print(f"\n--- {desc} ---")
    m_cfg = construir_modelo(Tx, Ty, n_a, n_y, n_pre, n_pos)
    s0_c, c0_c = estados_zeros(X.shape[0], n_pos)

    hist = m_cfg.fit(
        [X, s0_c, c0_c], Y_lista,
        epochs=20, batch_size=128, verbose=0
    )
    loss_f = hist.history['loss'][-1]
    print(f"  Loss final (20 épocas): {loss_f:.4f}")

    acertos = 0
    preds_cfg = []
    for h, ref in datas_item3:
        pred = traduzir(h, m_cfg, human_vocab, inv_machine_vocab,
                        Tx, Ty, n_a, n_pos)
        preds_cfg.append(pred)
        ok = "✓" if pred == ref else "✗"
        print(f"  {ok} '{h:<27}' → '{pred}'  (esperado '{ref}')")
        acertos += (pred == ref)

    resultados_cfg[desc] = {'loss': loss_f, 'acertos': acertos, 'preds': preds_cfg}

# Gráfico comparativo de loss por configuração
plt.figure(figsize=(8, 4))
labels = [c[2].split('(')[0].strip() for c in configuracoes]
losses = [resultados_cfg[c[2]]['loss'] for c in configuracoes]
plt.bar(labels, losses, color=['#4e8ef7','#43c6ac','#f7971e','#f64f59'])
plt.title('Loss final (20 épocas) por configuração de unidades')
plt.ylabel('Loss'); plt.xticks(rotation=15, ha='right')
plt.tight_layout()
plt.savefig('/content/loss_por_config.png', dpi=150)
plt.show()
print("Gráfico salvo em /content/loss_por_config.png")

"""## 12. Usar `plot_attention_map.py`"""

import sys
sys.path.insert(0, FILE_DIR + 'MS671-P2/')

import numpy as np
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
import matplotlib.pyplot as plt
from string_to_int import string_to_int
import plot_attention_map as pam_module

def int_to_string(ints, inv_vocab):
    return [inv_vocab.get(i, '?') for i in ints]

pam_module.np = np
pam_module.to_categorical = to_categorical
pam_module.Model = Model
pam_module.plt = plt
pam_module.string_to_int = string_to_int
pam_module.int_to_string = int_to_string

plot_attention_map = pam_module.plot_attention_map

# Testa com alguns exemplos
exemplos = [
    "3 May 1979",
    "21th of August 2016",
    "Tue 10 Jul 2007",
]

for ex in exemplos:
    print(f"Plotando atenção para: '{ex}'")
    plot_attention_map(model_pre, human_vocab, inv_machine_vocab,
                       ex, n_s=64, num=7)
    plt.show()

"""14. Tabela Comparativa Final"""

print("\n" + "=" * 75)
print("TABELA COMPARATIVA FINAL")
print("=" * 75)
print(f"  {'Entrada':<28} {'Esperado':^12} {'1 época':^12} {'50 épocas':^12} {'Pré-treinado':^14}")
print("  " + "-" * 75)

for h, m_ref in dataset[:10]:
    p1  = traduzir(h, model,     human_vocab, inv_machine_vocab, Tx, Ty, n_a, n_units_post)
    p50 = traduzir(h, model_50,  human_vocab, inv_machine_vocab, Tx, Ty, n_a, n_units_post)
    try:
        ppt = traduzir(h, model_pre, human_vocab, inv_machine_vocab, Tx, Ty, n_a, n_units_post_pre)
    except:
        ppt = "N/A"
    ok1  = "✓" if p1  == m_ref else "✗"
    ok50 = "✓" if p50 == m_ref else "✗"
    okpt = "✓" if ppt == m_ref else "✗"
    print(f"  {h:<28} {m_ref:^12} {ok1}{p1:^11} {ok50}{p50:^11} {okpt}{ppt:^13}")

print("\nCódigo finalizado com sucesso! ✓")